'use strict';
const utils = require('../../utils');

module.exports = [
  {
    type: 'input',
    name: 'appName',
    message: 'What is your app\s name?',
    default: utils.getAppName()
  },
  {
    type: 'input',
    name: 'description',
    message: 'Please provide a description of your app',
    default: 'Generated by generator-cic'
  },
  {
    type: 'input',
    name: 'repoUrl',
    message: 'What is the url for the repo of this project?',
    default: ''
  },
  {
    type: 'input',
    name: 'author',
    message: 'Who is the main author of this project?',
    default: ''
  },
  {
    type: 'input',
    name: 'ngModule',
    message: 'What is the name of your angular module?',
    default: 'app'
  }
];
